# -*- coding: utf-8 -*-
"""10-06-2026

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jxzH0_QHEMstSON3rL2ECUZPGMjrkAL1
"""

contacto = {
    "nombre": input("Ingresa nombre: "),
    "telefono": input("Ingresa teléfono: "),
    "email": input("Ingresa email: "),
    "edad": int(input("Ingresa edad: "))
}

opcion = ""

while opcion != "3":
    print("\n=== MENÚ ===")
    print("[1] Ver ficha")
    print("[2] Editar dato")
    print("[3] Salir")

    opcion = input("Elige una opción: ")

    if opcion == "1":
        print("\n--- FICHA ---")
        print("nombre   :", contacto["nombre"])
        print("telefono :", contacto["telefono"])
        print("email    :", contacto["email"])
        print("edad     :", contacto["edad"])

    elif opcion == "2":
        campo = input("¿Qué campo? ")
        nuevo_valor = input("Nuevo valor: ")
        contacto[campo] = nuevo_valor
        print("Actualizado.")

print("\n--- FICHA FINAL ---")
print("nombre   :", contacto["nombre"])
print("telefono :", contacto["telefono"])
print("email    :", contacto["email"])
print("edad     :", contacto["edad"])